# Generated by Django 4.2.3 on 2023-07-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField(verbose_name='端口号')),
                ('service', models.TextField(max_length=100, verbose_name='服务')),
                ('protocol', models.CharField(blank=True, default='未知', max_length=20, verbose_name='协议')),
                ('status', models.CharField(blank=True, default='未知', max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '端口列表',
                'verbose_name_plural': '端口列表',
            },
        ),
    ]
