# Generated by Django 4.2.3 on 2023-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_portlist_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portlist',
            name='service',
        ),
        migrations.AlterField(
            model_name='portlist',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=10, verbose_name='状态'),
        ),
    ]
